feat: return metadata headers
artipie/files-adapter pull request #109
Opened 2022-03-04 15:09 UTC by baudoliver7

When we request an file with URL paramter `meta` to `true`, we get headers :

```console
X-Artipie-MD5: md5sum
X-Artipie-CreatedAt: timestamp
X-Artipie-Size: 123
```

This feature is only available for `GET` and `HEAD` methods.

Fix: #107

2022-03-04 15:11 UTC, baudoliver7 commented
@artipie/maintainers ready to be reviewed :)

2022-03-16 06:44 UTC, olenagerasimova requested changes
@baudoliver7 thanks, there is a question I'd like to discuss with the arc

2022-03-16 06:44 UTC, olenagerasimova commented on src/main/java/com/artipie/files/FileMetaSlice.java
> +                                                            ).toString()
hm, I'm not sure that throwing exceptions in the case, when some property is not available, is the correct approach. I'd say should return what we can. @g4s8 what do you think?

2022-03-18 07:21 UTC, g4s8 commented on src/main/java/com/artipie/files/FileMetaSlice.java
> +                                                            ).toString()
Yes, correct. Let's return metadata that we have

2022-03-18 11:20 UTC, baudoliver7 commented on src/main/java/com/artipie/files/FileMetaSlice.java
> +                                                            ).toString()
Ok. Now, we return only metadata we have.

2022-03-18 11:39 UTC, olenagerasimova submitted a review, later dismissed
@baudoliver7 thanks

2022-03-22 09:07 UTC, g4s8 requested changes
@baudoliver7 thanks, please check a couple of comments

2022-03-22 09:07 UTC, g4s8 commented on src/main/java/com/artipie/files/FileMetaSlice.java
> +                    .supplyAsync(() -> new KeyFromPath(uri.getPath()))
No need to run this code asynchronously (it's much more expensive for CPU and less readable)

2022-03-22 09:07 UTC, g4s8 commented on src/main/java/com/artipie/files/FileMetaSlice.java
> +            final Optional<? extends String> mdfive = mtd.read(Meta.OP_MD5);
You can create a list of pairs or map of meta operator to header name:
```
OP_MD5: "X-Artipe-MD5"
OP_CREATED_AT: "X-Artipie-CretedAt"
OP_SIZE: "X-Artipie-Size"
```
and iterate over its keys and put header value with name from map value and value from operator reading value.

2022-03-22 10:42 UTC, baudoliver7 commented on src/main/java/com/artipie/files/FileMetaSlice.java
> +            final Optional<? extends String> mdfive = mtd.read(Meta.OP_MD5);
If meta values had the same types, it could be done. But one has `String` type, next has `Instant` type and another has `Long` type. At some point, we have to know what type we're dealing with.

```java
final Map<Meta.OpRWSimple<?>, String> fmtd = new HashMap<>();
fmtd.put(Meta.OP_MD5, "X-Artipie-MD5");
fmtd.put(Meta.OP_CREATED_AT, "X-Artipie-CreatedAt");
fmtd.put(Meta.OP_SIZE, "X-Artipie-Size");
final Map<String, String> hdrs = new HashMap<>();
for (Map.Entry<Meta.OpRWSimple<?>, String> entry : fmtd.entrySet()) {
    hdrs.put(entry.getValue(), mtd.read(entry.getKey()).get().toString());
}
```
Compiler cries at `mtd.read(entry.getKey())`

2022-03-22 10:49 UTC, baudoliver7 commented on src/main/java/com/artipie/files/FileMetaSlice.java
> +                    .supplyAsync(() -> new KeyFromPath(uri.getPath()))
Fixed

2022-03-22 11:18 UTC, g4s8 commented on src/main/java/com/artipie/files/FileMetaSlice.java
> +            final Optional<? extends String> mdfive = mtd.read(Meta.OP_MD5);
@baudoliver7 maybe we can use `Map<Meta.OpRWSimple<?>, ?>` here to read `Object` and put string representation of it to headers?

2022-03-22 11:37 UTC, baudoliver7 commented on src/main/java/com/artipie/files/FileMetaSlice.java
> +            final Optional<? extends String> mdfive = mtd.read(Meta.OP_MD5);
Fixed with `mtd.read(entry.getKey()).get().toString()` :)

2022-03-22 13:27 UTC, g4s8 approved these changes
@baudoliver7 thanks!

2022-03-22 13:27 UTC, merged