#37 - Authentication support in proxy
artipie/files-adapter pull request #39
Opened 2020-10-13 14:02 UTC by olegmoz

Closes #37 
Authentication support in proxy

2020-10-13 15:54 UTC, olenagerasimova requested changes
@olegmoz please check one suggestion

2020-10-13 15:54 UTC, olenagerasimova commented on src/test/java/com/artipie/files/FileProxySliceAuthIT.java
> +            new RsHasStatus(RsStatus.OK)
@olegmoz I'd suggest using `SliceHasResponse` here and also verify response body

2020-10-14 06:59 UTC, olegmoz commented on src/test/java/com/artipie/files/FileProxySliceAuthIT.java
> +            new RsHasStatus(RsStatus.OK)
@olenagerasimova thanks, just tried it and failed - it is incompatible with HTTP client slices. Created an issue about it: https://github.com/artipie/http/issues/251

2020-10-14 13:51 UTC, olenagerasimova approved these changes
@olegmoz thanks

2020-10-14 14:05 UTC, olegmoz commented
@olenagerasimova fixed the build, the fail was due to deprecated classes in newer HTTP release. Please re-review

2020-10-14 14:11 UTC, olenagerasimova approved these changes
@olegmoz thanks, all good

2020-10-14 14:21 UTC, merged

2020-10-14 15:01 UTC, 0crat commented
Job `gh:artipie/files-adapter#39` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/e2873836-d2dc-49d0-82fa-0219f46047e9, version: 0.54.5, hash: ${buildNumber} -->