Added cache to proxy
artipie/files-adapter pull request #44
Opened 2021-05-17 14:40 UTC by olenagerasimova

Part of #43 
Added cache to proxy: item is obtained from remote and cached, if remote does not respond with success, item is loaded from cache.

Created https://github.com/artipie/http/issues/305 to fix `RsWithBody`

2021-05-17 15:09 UTC, genryxy requested changes
@olenagerasimova thanks, please see comments

2021-05-17 15:09 UTC, genryxy commented on src/test/java/com/artipie/files/FileProxySliceTest.java
> +            "Incorrect status, 400 is expected",
@olenagerasimova looks like a typo as should be `404` instead of `400`

2021-05-17 15:09 UTC, genryxy commented on src/test/java/com/artipie/files/FileProxySliceTest.java
> +            "Cache storage should be empty",
@olenagerasimova please specify a negative scenario here

2021-05-17 15:09 UTC, genryxy commented on src/main/java/com/artipie/files/FileProxySlice.java
> +                                        .doOnTerminate(() -> term.complete(null));
@olenagerasimova why these lines are necessary? Probably to write `promise.complete(Optional.of(new Content.From(rsbody)))`

2021-05-18 07:13 UTC, olenagerasimova commented on src/main/java/com/artipie/files/FileProxySlice.java
> +                                        .doOnTerminate(() -> term.complete(null));
@genryxy I do not remember fail-case exactly, but sometime ago we catch a bug in maven proxy and spend a long time trying to understand what is wrong. I wrote `JettyClientSlicesAndVertxITCase` in http-client and we agreed with Oleg that this is the example for the proxies.

2021-05-18 07:14 UTC, olenagerasimova commented
@genryxy thanks, fixed and unswered

2021-05-18 08:17 UTC, genryxy approved these changes
@olenagerasimova thanks, got it

2021-05-18 08:24 UTC, olenagerasimova commented
@g4s8 could you please merge?

2021-05-18 08:26 UTC, merged