feat: list blobs in plain text
artipie/files-adapter pull request #89
Opened 2021-12-07 10:51 UTC by baudoliver7

Closes #77

- Introduce feature to list blobs in plain text
- Add a todo to test this feature
- Add a todo to list blobs in mime types `text/html` and `application/json`

2021-12-07 11:01 UTC, baudoliver7 commented
@artipie/maintainers ready to be reviewed :)

2021-12-07 14:54 UTC, genryxy requested changes
@baudoliver7 thanks, please check some comments

2021-12-07 14:54 UTC, genryxy commented on src/main/java/com/artipie/files/SliceListBlobs.java
> + * @since 0.1
`@since` tag is incorrect

2021-12-07 14:54 UTC, genryxy commented on src/main/java/com/artipie/files/SliceListBlobs.java
> +
I'd suggest to name `ListBlobsSlice` because usually classes for routing have postfix `slice`

2021-12-07 14:54 UTC, genryxy commented on src/main/java/com/artipie/files/SliceListBlobs.java
> +                                        Headers.EMPTY,
I think it would be better to add here header according to the result

2021-12-07 14:54 UTC, genryxy commented on src/main/java/com/artipie/files/SliceListBlobs.java
> +    ) {
could you please provide an example of case when this behaviour would differ from `KeyFromPath`

2021-12-07 15:19 UTC, baudoliver7 commented on src/main/java/com/artipie/files/SliceListBlobs.java
> +    ) {
Unfortunately, I do not currently have an example. But, I did it for flexibility as It is done in [SliceDownload](https://github.com/artipie/http/blob/master/src/main/java/com/artipie/http/slice/SliceDownload.java) for the primary constructor :
```java
/**
 * Slice by key from storage using custom URI path transformation.
 *
 * @param storage Storage
 * @param transform Transformation
 */
public SliceDownload(final Storage storage,
    final Function<String, Key> transform) {
    this.storage = storage;
    this.transform = transform;
}
```
We can thus use the second constructor to fit the usual case.

2021-12-07 15:23 UTC, baudoliver7 commented on src/main/java/com/artipie/files/SliceListBlobs.java
> +
Ok, let's do that :)

2021-12-07 15:30 UTC, baudoliver7 commented on src/main/java/com/artipie/files/SliceListBlobs.java
> +                                        Headers.EMPTY,
Ok. I will then suggest to change result type of function `BlobListPlainTextFormat` from `String` to `Map.Entry<String, String>` to have both content type and value in return. WDYT ?

2021-12-07 16:33 UTC, baudoliver7 commented on src/main/java/com/artipie/files/SliceListBlobs.java
> +                                        Headers.EMPTY,
please, check last changes to see how it looks like.

2021-12-07 16:34 UTC, baudoliver7 commented
@genryxy please, check my last changes and my comments.

2021-12-07 17:52 UTC, baudoliver7 commented on src/main/java/com/artipie/files/SliceListBlobs.java
> +                                        Headers.EMPTY,
finally, I introduced a new type to do things properly :-)

2021-12-07 20:56 UTC, genryxy commented on src/main/java/com/artipie/files/BlobListText.java
> +    String content();
@baudoliver7 thanks, one concern about naming. It looks like it more about keys or items but not about content of files. Probably it would be better to rename this method

2021-12-07 21:11 UTC, baudoliver7 commented on src/main/java/com/artipie/files/BlobListText.java
> +    String content();
@genryxy, you are right : `String content()` refers to the content of the `Text` formatted with keys of files found. We mean content of `BlobListText`. `BlobListText` is a `Text` here. That's why we use name `content`.

Perhaps, naming it in `String value()` could remove all ambiguities. WDYT ?

2021-12-07 21:23 UTC, genryxy commented on src/main/java/com/artipie/files/BlobListText.java
> +    String content();
@baudoliver7 let's rename as you suggested

2021-12-07 22:02 UTC, baudoliver7 commented on src/main/java/com/artipie/files/BlobListText.java
> +    String content();
Done in the latest changes :)

2021-12-07 22:10 UTC, genryxy submitted a review, later dismissed
@baudoliver7 thanks, looks good to me
@g4s8 please check/merge

2021-12-08 16:29 UTC, g4s8 requested changes
@baudoliver7 thanks, please check my comments

2021-12-08 16:29 UTC, g4s8 commented on src/main/java/com/artipie/files/BlobListText.java
> +    String value();
It's not clear from this method name and its javadoc what the value is.

2021-12-08 16:29 UTC, g4s8 commented on src/main/java/com/artipie/files/FilesSlice.java
> +                ),
We can swap these slices here: authentication would be the same for all kind of list slices, so it could be:
```java
new RtRulePath(
  ByMethodsRule.Standard.GET,
  new BasicAuthSlice(
    new SliceRoute(
      new RtRulePath(new RtRule.ByHeader(Accept.NAME, Pattern.compile("text/plain"))),
      new ListBlobsSlice(storage, BlobListPlainText::new),
    ), // and other routes by Accept header here
// ...
```

2021-12-08 16:29 UTC, g4s8 commented on src/main/java/com/artipie/files/ListBlobsSlice.java
> +        final Function<Collection<Key>, BlobListText> formatter
I like the idea of having a separate interface and classes for formatting list response text, but right now this class is just a data-holder: it computes all response text in constructor and returns it on data accessor method. Another problem is that it's using higher level abstraction (mime-type) which is related to HTTP layer (slice), and the cohesion of object variables is zero: it doesn't use mime-type internally - zero-cohesion means that this class could be safely decomposed.

So I'd suggest changing this class from `BlobListText` to `BlobListFormat` and use it instead of `formatter` param in slice constructor, this interface will have only key-list formatting behavior (which is now in constructor of BlobListText impl), and move mime-type field to `ListBlobsSlice` (http-layer), here this field will only increase the cohesion, since this object will use mime-type internally; also, this mime-type is a static property - it can't change in runtime, so there are no needs to create a method for this.

// CC: @genryxy

2021-12-08 16:29 UTC, g4s8 commented on src/main/java/com/artipie/files/BlobListText.java
> +public interface BlobListText {
No need to make it public

2021-12-09 00:07 UTC, baudoliver7 commented on src/main/java/com/artipie/files/ListBlobsSlice.java
> +        final Function<Collection<Key>, BlobListText> formatter
@g4s8 I got the idea. It's quite good for me :)

2021-12-09 00:07 UTC, baudoliver7 commented on src/main/java/com/artipie/files/BlobListText.java
> +public interface BlobListText {
Yes

2021-12-09 00:09 UTC, baudoliver7 commented on src/main/java/com/artipie/files/BlobListText.java
> +    String value();
We don't need it anymore after BlobListText refactoring :)

2021-12-09 00:09 UTC, baudoliver7 commented
@g4s8 please, take a look to my latest changes.

2021-12-10 14:33 UTC, g4s8 approved these changes
@baudoliver7 thanks

2021-12-10 14:34 UTC, merged